tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "act"
brew "python@3.11"
brew "awscli"
brew "git"
brew "go"
brew "jq"
brew "mas"
brew "nvm"
brew "pnpm"
brew "postgresql@14"
brew "python@3.10"
brew "terraform"
cask "dropbox"
cask "kindle"
cask "postman"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
